### ISSUE TITLE
Wijzig max_user_connections in MySQL naar 0

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Beheer#10]
Root zou dit moeten kunnen wijzigen met:
GRANT USAGE ON *.* TO deb99417_netkaart@localhost MAX_USER_CONNECTIONS 0;

**Comment by BaDu-HSN** [comment]
@HansNien : kan jij kijken of je via de beheersinterface van de hosting hier wat aan kan doen?

**Comment by HansNien** [comment]
Hmm, ik zal eens even kijken of ik iets aantref dat hiermee te maken heeft. Ogenblik.

**Comment by BaDu-HSN** [comment]
Als je my.cfg kan editten kan je het daarin zetten.

**Comment by HansNien** [comment]
Zo te zien is er geen ingebouwde tool waarmee ik iets kan doen op dit gebied. Ja okee, die zal er wel zijn, maar waar precies. Eens zien of ik het bewuste bestand kan vinden via phpMyAdmin.

**Comment by BaDu-HSN** [comment]
Anders even een ticket inschieten bij de helldesk

**Comment by HansNien** [comment]
Misschien wel beter ja. Tot nu toe kom ik niets tegen dat op my.cfg lijkt en ook bij andere configuratie-instellingen wijst er niets in die richting. Ik maak er werk van om het ze even voor te leggen, daar worden ze tenslotte voor betaald. Je hoort ervan.

**Comment by BaDu-HSN** [comment]
ow ding heet trouwens my.cnf sorry

**Comment by HansNien** [comment]
Niet erg, die was ik ook niet tegengekomen. Geen idee trouwens waar te zoeken. Bericht wordt nu opgesteld, met de goede bestandsnaam.

**Comment by HansNien** [comment]
(ticket verzonden, and now we'll wait)

**Comment by HansNien** [comment]
Ticket teruggekregen, je hebt email.

**Comment by BaDu-HSN** [comment]
FIXED
