### ISSUE TITLE
Naamsvermelding fotograaf van fotoos

### ISSUE THREAD

**Issue by Knarvel** [Hoogspanningsnet/Beheer#13]
De CC-licentie BY schrijft een naamsvermelding van de fotograaf van gebruikte fotoos voor. (ik denk hierbij aan fotoos van div. wiki's vooral uit het buitenlands) Daarom zou ik graag een extra veld in de objekten die een foto kunnen voeren willen voorstellen waar deze naam ingevuld kan worden. Ideaal zou het zijn dat dit veld direkt onder de foto wordt weergegeven en onderdrukt wordt als er niets instaat.

**Comment by BaDu-HSN** [comment]
Verplaatst naar GE (https://github.com/Hoogspanningsnet/GE-scripts/issues/26) en webomgeving (https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/189)
