### ISSUE TITLE
Sanity checks maken op de database

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Beheer#18]
Doel is eventuele fouten bij het intekenen via de database detecteren:

(Geef hieronder extra checks aan die je graag zou willen zien)

- [ ] Check of de combinatie stationsterreinnaam en spanning meer keren voorkomt (idem met iconen en verbindingen)
- [ ] Check of verbindingen eindigen in een terrein of een verbinding uiteinde (nagenoeg) raken
- [ ] Check of alle kabels de tekst "kabel" in de naam hebben
- [ ] Check of terreinen meer dan twee coordinaten hebben
- [ ] Check of verbindingen meer dan een coordinaat hebben
- [ ] Check of iconen een coordinaat hebben
- [ ] Check of iconen binnen een terrein staan

**Comment by BaDu-HSN** [comment]
Check of de combinatie stationsterreinnaam en spanning meer keren voorkomt:
`SELECT Spanning, Naam, count( ID ) FROM `Stations` GROUP BY Spanning DESC , Naam ASC HAVING COUNT( ID ) >1`

**Comment by HansNien** [comment]
Dank, goed idee.
Maar zijn alle objecten in de drie documenten ook opdiepbaar met een extra kolom waarin het objectnummer staat? Dat zou wissen veel sneller maken omdat één visuele controle dan afdoende is. De query moet dan op naam gaan en iets omvatten van dat twee of meer objecten met gelijke naam in de tabel worden getoond, telkens met de (niet identieke) objectnummers.

**Comment by HansNien** [comment]
Extra idee voor een check: bij terreinmarkeringen die geen 0 kV zijn (die dus spanning voeren) checken of er verbindingsuiteinden het terrein binnenlopen. Zo niet, dan kan het betekenen dat er geen verbindingen zijn gecarteerd, maar vooral ook dat er nog wat detailtekenwerk is voor het nauwkeuriger aansluiten van de verbindingsuiteinden.

**Comment by HansNien** [comment]
Eerste check van punt één (check op dubbele stationsterreinen) is voltooid en verwerkt.

**Comment by HansNien** [comment]
Tweede check van punt één (check op dubbele stationsnamen) is eveneens voltooid en verwerkt.

**Comment by HansNien** [comment]
Frank was bezig gegaan met de sanity check op dubbele verbindingen. Loopt dat nog en/of hoe ver is een en ander gevorderd?

**Comment by Knarvel** [comment]
Ik heb Oostenrijk geheel en Duitsland 380 en 220 kv gedaan.
Ik zou graag willen dat er weer nieuwe lijsten lijsten worden gegeneteerd en als gedeeld document op een google-drive worden gezet zodat iedereen die iets repareert, dit dan als opgelost uit de lijst kan wissen.

**Comment by HansNien** [comment]
Okee, dank. De enige lijst die dan nog nodig is, betreft dan de gedubbelde verbindingen. De andere twee lijsten met stations en terreinen zijn reeds doorgewerkt en kunnen we al afvinken.

**Comment by Knarvel** [comment]
Deze check zou regelmatig, bv om de 2 maanden, kunnen worden herhaald.
Overigens, bij de lijnen zaten geen echte dubbelingen, alleen de namen waren per abuis identiek

**Comment by BaDu-HSN** [comment]
Het is de beodeling dat bij de release netkaart V7.0 dit een deel gaat worden van de beheeromgeving.
Je kan dan altijd de actuele "problemen" bekijken via de beheerpagina.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#49
