### ISSUE TITLE
Verbeteren weergave van recente wijzigingen

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Beheer#21]
Afkomstig van shrek via het forum:
> De beheerderssite http://netkaart.hoogspanningsnet.com/beheer/beheer.php toont de recente aanpassingen al voor de gehele kaart, maar ik zou dit graag onderverdeeld zien per land, eventueel zelfs per deelnet. Zeker nu we zo internationaal aan het gaan zijn en half Europa erop hebben staan is de kans klein dat ik iets over België nog toevallig zie passeren. Ook voor diegenen die aan andere landen bezig zijn kan het misschien nuttig zijn te zien wat er onlangs allemaal werd toegevoegd of aangepast in dat deel van de kaart. 

Ik zie hier een aantal punten genoemd die wellicht nodig zijn:

- [ ] Zoek functie op wijzigingen aan item ...
- [ ] Tabbladen maken per land met wijzigingen per land (deelnet is lastiger aangezien we alleen bij verbindingen een deelnet administreren en niet bij masten etc.
- [ ] Weergave per item van gewijzigde velden met oude & nieuwe waarde (ook opnemen in het wijzigingen veld).
- [ ] Weergave van geraakte- en nieuwe items per importfile (iets ambitieuzer)
- [ ] Toevoegen import-reden aan de import mogelijkheid (zodat je in grote lijnen kan weergevevn welke wijzigingen er in het import bestand zitten)

Misschien zijn er meer suggesties? In dat geval graag hieronder toevoegen

**Comment by BavoLens** [comment]
Een eerste vraag lijkt mij: wat wordt er allemaal gelogd? Is elke actie sinds het begin van de kaart nog ergens aanwezig?

**Comment by BaDu-HSN** [comment]
Ja, het detail van de logging is wel steeds een ietsje beter geworden, maar iedere wijziging via het editscherm en iedere import en wis actie is gelogd. Daarbij is bijgehouden inieder geval de gebruikersnaam, het tijdstip en de gewijzigde velden.
Maar er kan natuurlijk meer detail toegevoegd worden zodat dat ook kan worden weergegeven.

**Comment by Knarvel** [comment]
Ik denk dat de het huidige formaat van de lijst met modificaties voldoet. (een regel per item). Wat ik mij als verbetering zou kunnen voorstellen is een filter per land, en eventueel per categorie (lijnen, stations, masten) en tenslotte een filter voor het aantal items in de lijst (50, 200, 1000, alles van het ingestelde land). Standaardwaarden: alle landen, alle categorieen, 200 lijnen geven dan dezelfde lijst als nu.  Ik stel dan 50 voor.
Verder zou het wenselijk zijn als bij de imports ook alle geimporteerde items een eigen regel in de log krijgen, maar dat is al ergens anders gezegd.

**Comment by BavoLens** [comment]
Hier ben ik het helemaal mee eens. Een dropdown-menutje met landkeuze en ééntje met een getalletje lijkt me voldoende.

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#46
