### ISSUE TITLE
Bulkwijziging van masten via excel ex- en import mogelijk maken

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Beheer#7]
Via de beheerders interface een verbinding selecteren en dan een excel krijgen met alle masten van die verbinding.
Import via beheerders interface (denk ook aan het log veld) en de wijzigingen database.
Alleen gewijzigde velden importeren en loggen

**Comment by Knarvel** [comment]
Lijkt mij een super handige en zinvolle productiviteits-accelerator! Graag doen.
Naast bovenstaande scope zou ik mij ook kunnen voorstellen een lijst volledig nieuwe masten per tabel in de DB te importeren. Dan moeten uiteraard wel wat meer gegevens in de tabel opgenomen worden, maar dat lijkt mij geen probleem.

**Comment by BaDu-HSN** [comment]
Zou ook moeten werken voor alle tabellen

**Comment by BaDu-HSN** [comment]
This issue was moved to Hoogspanningsnet/Netkaart-scripts#58
